config/routes.rb
Rails.application.routes.draw do
  resources :load_types
  resources :stops
  resources :drivers
  resources :vehicles
  resources :routes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :driver
  has_and_belongs_to_many :stops
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
    @cities = Stop.all
    @load = LoadType.all
  end

  # GET /routes/1/edit
  def edit
    @cities = Stop.all
    @load = LoadType.all
  end

  # POST /routes
  # POST /routes.json
  def create
    @cities = Stop.all
    @load = LoadType.all
    @route = Route.new(route_params)
    vehiculos = []
    ids_driver = []
    var_id = 0


    # buscar driver con las preferencias anteriores viendo que no tenga rutas asociadas en el dia y no se repita
    carga = if @route['load_type'].nil? then 1 else @route['load_type'] end
    cities = if @route['cities'].nil? then 1 else @route['cities'] end

    vehicles = Vehicle.where(load_type: carga)
    vehicles.each do |ve|
      ruta = Route.where(vehicle_id: ve.id).where('start_at < ? AND ends_at > ?', @route['ends_at'], @route['start_at'])
      if ruta.count == 0
        vehiculos << ve.id
      end
    end
    salida = false
    mensaje = ""
    if !vehiculos.empty?

      # buscar conductor si tiene o no vehiculo
      vehiculos.each do |v|
        veh = Vehicle.find_by_id(v)
        if veh.driver_id.nil?
          #Buscar driver sin vehiculos y ciudad preferida
          drivers = Driver.select(:id).where(vehicle_owner: false, stop_id: @route['cities'])
          if !drivers.nil?
            drivers.each do |d|
              driver = Route.where(driver_id: d.id)
              ids_driver << d.id
              if driver.empty?
                var_id = d.id
                break
              end
            end
            if var_id == 0
              ids_driver.shuffle!
              var_id = ids_driver[0]
            end
            @route.driver_id = var_id
            @route.vehicle_id = veh.id
            salida = true
            break
          else
            drivers = Driver.where(vehicle_owner: false)
            if !driver.nil?
              drivers.each do |d|
                driver = Route.where(driver_id: d.id)
                ids_driver << d.id
                if driver.empty?
                  var_id = d.id
                  break
                end
              end
              if var_id == 0
                ids_driver.shuffle!
                var_id = ids_driver[0]
              end
              @route.driver_id = var_id
              @route.vehicle_id = veh.id
              salida = true
              break
            else
              mensaje = "No encontro conductor"
            end
          end
          puts "****************************************"
          puts @route.driver_id
        else
          puts "Algo #{ veh.id}"
          @route.driver_id = veh.driver_id
          @route.vehicle_id = veh.id
          salida = true
          break
        end
      end
    else
      mensaje = "No existen vehiculos disponibles en ese horario"
    end
    @route.load_type = carga
    @route.cities = cities

    respond_to do |format|
      if salida
          #agregar los datos a la tabla de ruta y registro de rutas
          if @route.save
            format.html { redirect_to @route, notice: 'Route was successfully created.' }
            format.json { render :show, status: :created, location: @route }
          else
            format.html { redirect_to @route, notice: mensaje }
            format.json { render json: @route.errors, status: :unprocessable_entity }
          end
      else
        puts "NO salio"
        format.html { redirect_to @route, notice: mensaje }
        format.json { render json: @route.errors, status: :unprocessable_entity, notice: mensaje }
      end
    end

  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:start_at, :ends_at, :load_type, :load_sum, :cities, :stops_amount, :vehicle_id, :driver_id)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at %>
  </div>

  <div class="field">
    <%= form.label :load_type %>
    <%= form.select(:load_type, @load.collect {|l| [h(l.name), l.id] }, { include_blank: 'Select One'}) %>
  </div>

  <div class="field">
    <%= form.label :cities %>
    <%= form.select(:cities, @cities.collect {|r| [h(r.name), r.id] }, { include_blank: 'Select One'}) %>
  </div>

  <div class="actions">
    <%= form.submit('Crear Ruta Manual') %>
  </div>
  <div class="actions">
    <%= form.button('Ver Ruta', type: :button) %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Driver</th>
      <th>Ruta</th>
      <th>Start at</th>
      <th>Ends at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.vehicle_id %></td>
        <td><%= route.driver_id %></td>
        <td><%= route.id %></td>
        <td><%= route.start_at %></td>
        <td><%= route.ends_at %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @route.start_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @route.ends_at %>
</p>

<p>
  <strong>Load type:</strong>
  <%= @route.load_type %>
</p>

<p>
  <strong>Cities:</strong>
  <%= @route.cities %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>