config/routes.rb
Rails.application.routes.draw do
  resources :load_types
  resources :stops
  resources :drivers
  resources :vehicles
  resources :routes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :routes
  has_and_belongs_to_many :vehicles
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
    @vehicle = Vehicle.all
    @cities = Stop.all
  end

  # GET /drivers/1/edit
  def edit
      @vehicle = Vehicle.all
      @cities = Stop.all
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)
    owner = @driver["vehicle_owner"]
    id_veh = @driver["vehicle_id"]
    vehicle = Vehicle.find_by_id(id_veh)
    if owner == '0'
      @driver['vehicle_id'] = nil
      vehicle.driver_id = nil
    end

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @drivers = (driver_params)
      owner = @drivers["vehicle_owner"]
      id_veh = @drivers["vehicle_id"]
      if !id_veh.empty?
        vehicle = Vehicle.find_by_id(id_veh)
        if owner == '0'
          @drivers['vehicle_id'] = nil
          vehicle.driver_id = nil
        else
          vehicle.driver_id = params['id']
        end
        vehicle.save
      end
      if @driver.update(@drivers)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :phone, :email, :vehicle_id, :vehicle_owner, :stop_id)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :stop_id, value: "Parada Favorita" %>
    <%= form.select(:stop_id, @cities.collect {|r| [h(r.name), r.id] }, { include_blank: 'Select One'}) %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.select(:vehicle_id, @vehicle.collect {|r| [h(r.capacity), r.id] }, { include_blank: 'Select One'}) %>
  </div>

  <div class="field">
    <%= form.label :vehicle_owner %>
    <%= form.check_box :vehicle_owner %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Vehicle</th>
      <th>Vehicle owner</th>
      <th>Favorite Stop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.phone %></td>
        <td><%= driver.email %></td>
        <td><%= driver.vehicle_id %></td>
        <td><%= driver.vehicle_owner %></td>
        <td><%= driver.stop_id %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @driver.vehicle_id %>
</p>

<p>
  <strong>Vehicle owner:</strong>
  <%= @driver.vehicle_owner %>
</p>
<p>
  <strong>Favorite Stop:</strong>
  <%= @driver.stop_id %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>