config/routes.rb
Rails.application.routes.draw do
  resources :load_types
  resources :stops
  resources :drivers
  resources :vehicles
  resources :routes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :routes
  has_and_belongs_to_many :drivers
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @driver = Driver.all
    @load = LoadType.all
  end

  # GET /vehicles/1/edit
  def edit
    @driver = Driver.all
    @load = LoadType.all
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:capacity, :load_type, :driver_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :load_type %>
    <%= form.select(:load_type, @load.collect {|l| [h(l.name), l.id] }, { include_blank: 'Select One'}) %>    
  </div>

  <div class="field">
    <%= form.label :driver_id %>
    <%= form.select(:driver_id, @driver.collect {|r| [h(r.name), r.id] }, { include_blank: 'Select One'}, disabled:"disabled") %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Capacity</th>
      <th>Load type</th>
      <th>Driver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.capacity %></td>
        <td><%= vehicle.load_type %></td>
        <td><%= vehicle.driver_id %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacity:</strong>
  <%= @vehicle.capacity %>
</p>

<p>
  <strong>Load type:</strong>
  <%= @vehicle.load_type %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @vehicle.driver_id %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>